"""add machine storage path

Revision ID: 3a3ff6264490
Revises: 80fb230b718a
Create Date: 2026-09-24 22:19:04.636264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a3ff6264490'
down_revision: Union[str, Sequence[str], None] = '80fb230b718a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machine', sa.Column('storage_path', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('machine', 'storage_path')
    # ### end Alembic commands ###
