"""add user_id business key to user table

Revision ID: dc842d66120d
Revises: f3b38637b35a
Create Date: 2026-09-11 12:44:45.484159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc842d66120d'
down_revision: Union[str, Sequence[str], None] = 'f3b38637b35a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_id', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_user_user_id'), 'user', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_user_id'), table_name='user')
    op.drop_column('user', 'user_id')
    # ### end Alembic commands ###
