"""add company fields to client and person fields to user

Revision ID: f3b38637b35a
Revises: db59a68f3eac
Create Date: 2026-09-07 09:35:08.801165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3b38637b35a'
down_revision: Union[str, Sequence[str], None] = 'db59a68f3eac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('company_id', sa.String(length=20), nullable=True))
    op.add_column('client', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('client', sa.Column('sector', sa.String(length=100), nullable=True))
    op.add_column('client', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('client', sa.Column('currency', sa.String(length=10), nullable=True))
    op.add_column('client', sa.Column('locale', sa.String(length=10), nullable=True))
    op.create_index(op.f('ix_client_company_id'), 'client', ['company_id'], unique=True)
    op.add_column('user', sa.Column('first_name', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('job_title', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('visibility', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###
    op.create_check_constraint(
        'ck_user_visibility',
        'user',
        "visibility IN ('full', 'technician', 'commercial')",
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint('ck_user_visibility', 'user', type_='check')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'visibility')
    op.drop_column('user', 'job_title')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    op.drop_index(op.f('ix_client_company_id'), table_name='client')
    op.drop_column('client', 'locale')
    op.drop_column('client', 'currency')
    op.drop_column('client', 'city')
    op.drop_column('client', 'sector')
    op.drop_column('client', 'country')
    op.drop_column('client', 'company_id')
    # ### end Alembic commands ###
